### ISSUE TITLE
Todo not recognized in comment tag php with html

### ISSUE THREAD

**Issue by mv-stns** [heightapp/vscode#1]
![CleanShot 2022-09-14 at 14 08 27@2x](https://user-images.githubusercontent.com/21103251/190149863-2c1b5a66-dfe0-472e-a389-9047715c2b44.png)

HTML Code inside of PHP code is not being recognized as a "todo"-command…
Otherwise if i add the "//" like in the script tag the ID is being added and transformed to the tasks.

PS:
If the Visual Studio Code extension & the npm tool is being installed and configured, tasks appear twice in the tasks menue
<img width="1616" alt="CleanShot 2022-09-14 at 14 06 47@2x" src="https://user-images.githubusercontent.com/21103251/190149491-446a9d07-a765-4c8f-b224-a7149264361f.png">

**Comment by mv-stns** [comment]
This type of comment formatting seems to work though, fine with that 😆 
<img width="1760" alt="CleanShot 2022-09-14 at 14 11 13@2x" src="https://user-images.githubusercontent.com/21103251/190150231-fe75a650-2c75-4f31-9142-6bfe7e951882.png">

**Comment by sebastienvillar** [comment]
This is now supported in the latest version :)
